# Logfile created on 2014-01-27 15:13:42 -0300 by logger.rb/36483
*** Below you'll find the most recent exception thrown, this will likely (but not certainly) be the exception that made your application exit abnormally ***
#<ThreadError: can't be called from trap context>
*** Below you'll find all the exception objects in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
#<IOError: stream closed>
#<NoMemoryError: failed to allocate memory>
#<SystemStackError: stack level too deep>
#<#<Class:0x007f88a28dc750>: exception reentered>
#<ThreadError: can't be called from trap context>
#<ThreadError: can't be called from trap context>
